{{- if .Values.orgsConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zitadel-rbac-mapper.fullname" . }}-config
  labels:
    {{- include "zitadel-rbac-mapper.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.orgsConfig | toYaml | nindent 4 }}
{{- end }}
