{{- if .Values.rules }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zitadel-rbac-mapper.fullname" . }}-rules
  labels:
    {{- include "zitadel-rbac-mapper.labels" . | nindent 4 }}
data:
  rules.yaml: |
    {{- if .Values.rules.orgs }}
    {{- .Values.rules | toYaml | nindent 4 }}
    {{- else }}
    orgs:
      - id: {{ .Values.rules.orgId | default "" | quote }}
        name: {{ .Values.rules.orgName | default "" | quote }}
        rules:
        {{- .Values.rules.entries | toYaml | nindent 8 }}
    {{- end }}
{{- end }}
