name: Renovate

on:
  schedule:
    - cron: "0 0 * * *" # daily midnight UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-lates
    timeout-minutes: 30t
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: token
        with:
          client-id: ${{ vars.RENOVATE_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}

      - uses: renovatebot/github-action@e09d604f8f803bb527bd8321ed5be06c460b8682 # v46.2.2
        with:
          token: ${{ steps.token.outputs.token }}
        env:
          LOG_LEVEL: info
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          GITHUB_COM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
